export enum PrismaErrors {
  DUPLICATED = "P2002",
  FOREIGN_KEY_CONSTRAINT = "P2003",
  NOT_FOUND = "P2025",
  NOT_CONNECTED = "P2017",
}

export enum TokenActivity {
  RESET_PASSWORD = "RESET_PASSWORD",
  AUTHENTICATE = "AUTHENTICATE",
}
