openapi: "3.0.0"
info:
  title: Microblog
  version: "1.0.0"
servers:
  - url: "/api"
tags:
  - name: "health"
    description: "Monitoring routes for the server"
  - name: "auth"
  - name: "users"
  - name: "posts"
  - name: "comments"
paths:
  /health:
    get:
      tags:
        - "health"
      responses:
        "200":
          description: "Server's date"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  status:
                    enum: ["ok"]
                    type: "string"
                  uptime:
                    type: "string"

  /auth/register:
    post:
      tags:
        - "auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              required:
                - "first_name"
                - "last_name"
                - "email"
                - "password"
              properties:
                first_name:
                  type: "string"
                last_name:
                  type: "string"
                email:
                  type: "string"
                password:
                  type: "string"
      responses:
        "200":
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Register"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /auth/sign-in:
    post:
      tags:
        - "auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              required:
                - "email"
                - "password"
              properties:
                email:
                  type: "string"
                password:
                  type: "string"
      responses:
        "200":
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignIn"
        "401":
          description: "Forbidden"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /auth/reset-password:
    post:
      summary: "Send an email to set a new password"
      tags:
        - "auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              required:
                - "email"
              properties:
                email:
                  type: "string"
      responses:
        "204":
          description: "Empty body"
  /auth/set-password:
    patch:
      summary: "Update password"
      tags:
        - "auth"
      parameters:
        - name: "token"
          description: "token to protect user"
          in: "query"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              required:
                - "password"
              properties:
                password:
                  type: "string"
      responses:
        "204":
          description: "Empty body"
      security:
        - api_key: []
  /auth/sign-out:
    post:
      tags:
        - "auth"
      responses:
        "204":
          description: "Empty body"
        "412":
          description: "no token received"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - api_key: []

  /users/confirm:
    post:
      summary: "Confirm account"
      tags:
        - "users"
      parameters:
        - name: "token"
          in: "query"
          schema:
            type: "string"
      responses:
        "204":
          description: "Empty body"
        "422":
          description: "Unprocessable Token"

  /users/me:
    get:
      summary: "Retrieve own account profile"
      tags:
        - "users"
      responses:
        "200":
          description: "Account"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
      security:
        - api_key: []
    patch:
      summary: "Update own profile"
      tags:
        - "users"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        "200":
          description: "Updated profile"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
      security:
        - api_key: []
  /users/me/password: {}
  /users/me/posts:
    get:
      summary: "Retrieves all posts from own account"
      tags:
        - "posts"
      responses:
        "200":
          description: "All posts from account"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/PostWithoutAuthor"
      security:
        - api_key: []
  /users/me/comments:
    get:
      summary: "Retrieves all comments from own account"
      tags:
        - "comments"
      responses:
        "200":
          description: "All comments from account"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/CommentWithoutAuthor"
      security:
        - api_key: []
  /users/{accountId}:
    get:
      summary: "Retrieve account profile"
      tags:
        - "users"
      parameters:
        - $ref: "#/components/parameters/accountId"
      responses:
        "200":
          description: "Account"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "404":
          description: "Account not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /users/{accountId}/posts:
    get:
      summary: "Retrieves all posts from account"
      tags:
        - "posts"
      parameters:
        - $ref: "#/components/parameters/accountId"
      responses:
        "200":
          description: "All posts from account"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/PostWithoutAuthor"
        "404":
          description: "Account not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /posts:
    get:
      summary: "Retrieves all posts"
      tags:
        - "posts"
      responses:
        "200":
          description: "All posts"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Post"
    post:
      summary: "Creates a new post"
      tags:
        - "posts"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              required:
                - "title"
                - "content"
              properties:
                title:
                  type: "string"
                category:
                  type: "string"
                content:
                  type: "string"
                draft:
                  type: "boolean"
                like:
                  type: "boolean"
      responses:
        "201":
          description: "New post created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
      security:
        - api_key: []
  /posts/{postId}:
    get:
      summary: "Retrieves a post"
      tags:
        - "posts"
      parameters:
        - $ref: "#/components/parameters/postId"
      responses:
        "200":
          description: "A post"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
        "404":
          description: "Post not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: "Update own post"
      tags:
        - "posts"
      parameters:
        - $ref: "#/components/parameters/postId"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                title:
                  type: "string"
                category:
                  type: "string"
                content:
                  type: "string"
                draft:
                  type: "boolean"
                like:
                  type: "boolean"
      responses:
        "200":
          description: "Updated post"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
      security:
        - api_key: []
    delete:
      summary: "Delete own post"
      tags:
        - "posts"
      parameters:
        - $ref: "#/components/parameters/postId"
      responses:
        "200":
          description: "Deleted post"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"
      security:
        - api_key: []
  /posts/{postId}/like:
    patch:
      summary: "Like/dislike a post"
      tags:
        - "posts"
      parameters:
        - $ref: "#/components/parameters/postId"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                like:
                  type: "boolean"
      responses:
        "204":
          description: "Empty content"
      security:
        - api_key: []
  /posts/{postId}/report:
    post:
      summary: "Report a post to moderator"
      tags:
        - "posts"
      parameters:
        - $ref: "#/components/parameters/postId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              required:
                - "message"
              properties:
                message:
                  type: "string"
      responses:
        "204":
          description: "Empty body"
      security:
        - api_key: []
  /posts/{postId}/likes:
    get:
      summary: "Accounts that gave like to post"
      tags:
        - "posts"
      parameters:
        - $ref: "#/components/parameters/postId"
      responses:
        "200":
          description: "Accounts"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Account"
        "404":
          description: "Post not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /posts/{postId}/comments:
    get:
      summary: "Retrieves post's comments"
      tags:
        - "comments"
      parameters:
        - $ref: "#/components/parameters/postId"
      responses:
        "200":
          description: "Comments"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Comment"
        "404":
          description: "Post not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: "Creates a new comment"
      tags:
        - "comments"
      parameters:
        - $ref: "#/components/parameters/postId"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              required:
                - "content"
              properties:
                content:
                  type: "string"
                draft:
                  type: "boolean"
                like:
                  type: "boolean"
      responses:
        "201":
          description: "New comment created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
      security:
        - api_key: []

  /comments/{commentId}:
    get:
      summary: "Retrieves a comment"
      tags:
        - "comments"
      parameters:
        - $ref: "#/components/parameters/commentId"
      responses:
        "200":
          description: "A comment"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
        "404":
          description: "Comment not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: "Update own comment"
      tags:
        - "comments"
      parameters:
        - $ref: "#/components/parameters/commentId"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                content:
                  type: "string"
                draft:
                  type: "boolean"
                like:
                  type: "boolean"
      responses:
        "200":
          description: "Updated comment"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
      security:
        - api_key: []
    delete:
      summary: "Delete own comment"
      tags:
        - "comments"
      parameters:
        - $ref: "#/components/parameters/commentId"
      responses:
        "200":
          description: "Deleted comment"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comment"
      security:
        - api_key: []
  /comments/{commentId}/like:
    patch:
      summary: "Like/dislike a comment"
      tags:
        - "comments"
      parameters:
        - $ref: "#/components/parameters/commentId"
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              properties:
                like:
                  type: "boolean"
      responses:
        "204":
          description: "Empty content"
      security:
        - api_key: []
  /comments/{commentId}/report:
    post:
      summary: "Report a comment to moderator"
      tags:
        - "comments"
      parameters:
        - $ref: "#/components/parameters/commentId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              required:
                - "message"
              properties:
                message:
                  type: "string"
      responses:
        "204":
          description: "Empty body"
      security:
        - api_key: []
  /comments/{commentId}/likes:
    get:
      summary: "Accounts that gave like to comment"
      tags:
        - "comments"
      parameters:
        - $ref: "#/components/parameters/commentId"
      responses:
        "200":
          description: "Accounts"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Account"
        "404":
          description: "Comment not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Register:
      type: "object"
      properties:
        token:
          type: "string"
        expiration:
          type: "integer"
    SignIn:
      type: "object"
      properties:
        token:
          type: "string"
        expiration:
          type: "integer"
    Error:
      type: "object"
      properties:
        statusCode:
          type: "integer"
        message:
          type: "string"
        errors:
          type: "array"
          items:
            type: "object"
            properties:
              property:
                type: "string"
              constraint:
                type: "array"
                items:
                  type: "string"
    Account:
      type: "object"
      properties:
        uuid:
          type: "string"
        first_name:
          type: "string"
        last_name:
          type: "string"
        email:
          type: "string"
        configurations:
          type: "object"
          properties:
            name_public:
              type: "boolean"
            email_public:
              type: "boolean"
    PostWithoutAuthor:
      type: "object"
      properties:
        uuid:
          type: "string"
        title:
          type: "string"
        category:
          type: "string"
        content:
          type: "string"
        likes:
          type: "integer"
        comments:
          type: "array"
          items:
            $ref: "#/components/schemas/Comment"
        createdAt:
          type: "string"
    Post:
      allOf:
        - $ref: "#/components/schemas/PostWithoutAuthor"
        - type: "object"
          properties:
            author:
              $ref: "#/components/schemas/Account"
    CommentWithoutAuthor:
      type: "object"
      properties:
        uuid:
          type: "string"
        content:
          type: "string"
        likes:
          type: "integer"
        createdAt:
          type: "string"
    Comment:
      allOf:
        - $ref: "#/components/schemas/CommentWithoutAuthor"
        - type: "object"
          properties:
            author:
              $ref: "#/components/schemas/Account"

  parameters:
    postId:
      name: "postId"
      in: "path"
      description: "The post's uuid"
      required: true
      schema:
        type: "string"
    commentId:
      name: "commentId"
      in: "path"
      description: "The comment's uuid"
      required: true
      schema:
        type: "string"
    accountId:
      name: "accountId"
      in: "path"
      description: "The account's uuid"
      required: true
      schema:
        type: "string"

  securitySchemes:
    api_key:
      type: "apiKey"
      name: "authorization"
      in: "header"
      description: "Bearer <YOUR_TOKEN>"
